---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-prime-video
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: amazon
    containers:
    - name: amazon-containers
      image: devil678/amazon-prime-video
      ports:
      - containerPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: amazon-service
spec:
  type: LoadBalancer
  selector:
    app: amazon
  ports:
  - port: 80
    targetPort: 3002
